export interface GlossaryTerm {
  id: string;
  term: string;
  reading?: string;
  english?: string;
  category: 'basic' | 'drawing' | 'spacing' | 'format';
  shortSummary: string;
  easyExplanation: string;
  appFeatureTip?: string;
  badge?: string;
}

export const GLOSSARY_CATEGORIES = [
  { id: 'all', label: 'すべて' },
  { id: 'basic', label: '基礎・文字' },
  { id: 'drawing', label: '線・パス・作図' },
  { id: 'spacing', label: '余白・配置・メトリクス' },
  { id: 'format', label: 'ファイル形式・出力' },
];

export const FONT_GLOSSARY: GlossaryTerm[] = [
  {
    id: 'glyph',
    term: 'グリフ',
    reading: 'ぐりふ',
    english: 'Glyph',
    category: 'basic',
    shortSummary: '文字の形状を表す輪郭・デザインデータ',
    easyExplanation: 'フォントの世界では、1文字分のデザインや輪郭データのことを「グリフ」と呼びます。同じ文字コード（例えば「あ」）であっても、丸文字や毛筆、明朝体などデザインごとに異なるグリフが存在します。',
    appFeatureTip: '左側の文字一覧から作字したいグリフを選択して作業を開始できます。',
    badge: '基本',
  },
  {
    id: 'em-square',
    term: '仮想ボディ (字面枠 / EM)',
    reading: 'かそうぼでぃ',
    english: 'EM Square / Body Box',
    category: 'spacing',
    shortSummary: '文字を配置する基準となる正方形の枠（1000×1000基準）',
    easyExplanation: 'デジタルフォントは、通常 1000×1000 単位の正方形の枠組みを基準として設計されます。この基準枠を「仮想ボディ」と呼びます。漢字（85%枠）や仮名（78%枠）など枠に対してどれくらいの大きさで描くかで文字のバランスが決まります。',
    appFeatureTip: 'キャンバス中央の薄緑色の点線枠（850×850）を目安に収めると、文章にした際にバランスよく整います。',
    badge: '超重要',
  },
  {
    id: 'side-bearing',
    term: 'サイドベアリング (左右の余白)',
    reading: 'さいどべありんぐ',
    english: 'LSB / RSB / Advance Width',
    category: 'spacing',
    shortSummary: '隣り合う文字との間隔を保つための左右の余白',
    easyExplanation: '文字同士が接触せず自然に読めるよう、左右に設ける余白領域のことです。左側の余白を LSB (Left Side Bearing)、右側の余白を RSB (Right Side Bearing)、全体の幅を送り幅（Advance Width）と呼びます。',
    appFeatureTip: 'ショートカット「Shift + Alt + S」を押すか、右側パネルの「字幅自動設定」をクリックすることで自動計算できます。',
    badge: '基本メトリクス',
  },
  {
    id: 'bezier-curve',
    term: 'ベジェ曲線 / パス',
    reading: 'べじぇきょくせん',
    english: 'Bézier Curve / Path',
    category: 'drawing',
    shortSummary: '拡大・縮小しても輪郭が劣化しない滑らかなベクター曲線',
    easyExplanation: '一般的な画像ファイル（PNGやJPEG）はピクセルの集合体ですが、フォントは数式で輪郭を表現する「ベクター形式」で作成されます。そのため、スマートフォン画面から大型看板の印刷まで、どのような解像度でも常に鮮明に表示されます。',
    appFeatureTip: '筆ツール [B] でフリーハンド描画を行うと、アプリが自動で滑らかなベジェ輪郭に変換します。',
    badge: '基本',
  },
  {
    id: 'node-anchor',
    term: 'アンカーポイント / ノード',
    reading: 'あんかーぽいんと / のーど',
    english: 'Anchor Point / Node',
    category: 'drawing',
    shortSummary: '曲線の位置と曲がり具合を決定する制御点',
    easyExplanation: 'ベジェ曲線の輪郭を構成する通過点です。アンカーポイントから伸びる「ハンドル」の長さや向きを調整することで、曲線の膨らみや角度を変更できます。',
    appFeatureTip: 'ノード編集ツール [A] でアンカーポイントやハンドルを選択し、ドラッグして形状を微調整できます。',
  },
  {
    id: 'remove-overlap',
    term: '重複除去 ( Remove Overlap / パス結合 )',
    reading: 'じゅうふくじょきょ',
    english: 'Remove Overlap / Union',
    category: 'drawing',
    shortSummary: '重なり合った複数のパーツを1つのクリーンな輪郭に合体する処理',
    easyExplanation: '「さんずい」や「へん・つくり」など、手書きの線や幾何学パーツが交差して重なっている部分を統合し、内側の余分な線を自動削除する機能です。出力フォントのデータ構造がキレイになります。',
    appFeatureTip: '上部バーの「重複除去」ボタンを押すと、文字全体の交差パスがワンタッチで1つの輪郭に合体されます。',
    badge: '便利機能',
  },
  {
    id: 'extrema',
    term: '極値ノード ( Extrema )',
    reading: 'きょくちのーど',
    english: 'Extrema Nodes',
    category: 'drawing',
    shortSummary: '曲線の最上点・最下点・最左点・最右点にある重要なノード',
    easyExplanation: '円や曲線のいちばん上のてっぺん、いちばん下の底、いちばん左、いちばん右の位置に配置されるアンカーポイントです。極値にノードがあると、フォントのレンダリングや拡大縮小で曲線の丸みが歪まなくなります。',
    appFeatureTip: '品質チェック画面から「極値ノード自動配置」を実行すると、曲線の端点へ自動的にノードを追加できます。',
    badge: '品質向上',
  },
  {
    id: 'simplify',
    term: 'パスの単純化 (Simplify)',
    reading: 'ぱすのたんじゅんか',
    english: 'Path Simplification',
    category: 'drawing',
    shortSummary: '余分なアンカーポイントを削減し、滑らかな曲線に最適化する機能',
    easyExplanation: 'フリーハンドで描画した直後はアンカーポイントが多くなりがちです。パスの単純化を実行することで、文字本来のシルエットを保ちながら余分な点を整理し、容量の軽量化と滑らかな輪郭への最適化を同時に行います。',
    appFeatureTip: '描画後に「Alt + S」キーを押すか、上部バーの「単純化」ボタンからいつでもワンタッチで実行できます。',
    badge: '推奨',
  },
  {
    id: 'winding-direction',
    term: 'パスの方向 / くり抜き規則 (Winding)',
    reading: 'ぱすのほうこう / わいんでぃんぐ',
    english: 'Winding Direction / Fill Rule',
    category: 'drawing',
    shortSummary: '外側の輪郭と内側の穴（くり抜き）を区別するための線の向き',
    easyExplanation: '「日」や「口」や「O」のように穴があいた文字では、外側の線と内側の穴の線の描く向き（時計回り・反時計回り）が逆になっている必要があります。向きが合っていないと、穴の部分が黒く塗りつぶされることがあります。',
    appFeatureTip: '本アプリでは出力時に全文字のパス方向を自動正滑化するため、穴が黒く塗りつぶされる心配はありません。',
  },
  {
    id: 'expand-stroke',
    term: 'ストローク拡張 (線の輪郭化)',
    reading: 'すとろーくかくちょう',
    english: 'Expand Stroke / Outline',
    category: 'drawing',
    shortSummary: '一本の線の太さを、塗りつぶし可能な袋文字の輪郭データに変換する処理',
    easyExplanation: 'ペンツールで描いた1本の線（単一パス）に太さを与え、周囲を囲む「面（塗りデータ）」へと変換する処理です。太いゴシック体や袋文字を作成する際に活用されます。',
    appFeatureTip: '「機能」メニューから線の太さを指定してストローク拡張を実行できます。',
  },
  {
    id: 'baseline',
    term: 'ベースライン',
    reading: 'べーすらいん',
    english: 'Baseline',
    category: 'spacing',
    shortSummary: '欧文や数字の配置基準となる水平ライン',
    easyExplanation: 'アルファベットの大文字や多くの小文字、数字などの底面が揃う基準となる水平線です。日本語フォントであっても、半角英数字や記号との混植時に文字の下端が揃うようベースラインが設定されます。',
    appFeatureTip: 'キャンバス下部に表示される水平線がベースライン（Y=200）です。英小文字の「g」や「y」の下部はベースラインより下へ配置します。',
  },
  {
    id: 'ascender-descender',
    term: 'アセンダ / ディセンダ',
    reading: 'あせんだ / でぃせんだ',
    english: 'Ascender / Descender',
    category: 'spacing',
    shortSummary: '小文字の基準高さを超えて上下に伸びる領域',
    easyExplanation: '英小文字「b, d, h」などの上方向に伸びる部分をアセンダ、英小文字「g, j, p, q, y」などのベースラインより下方向に伸びる部分をディセンダと呼びます。',
    appFeatureTip: 'ガイド線の「欧文4線」を有効にすることで、アセンダ線やディセンダ線を目安にした正確な欧文作字が行えます。',
  },
  {
    id: 'kerning',
    term: 'カーニング (文字間ペア調整)',
    reading: 'かーにんぐ',
    english: 'Kerning',
    category: 'spacing',
    shortSummary: '特定の文字ペア間で発生する不自然な隙間を詰める文字間調整',
    easyExplanation: '文字の形状によって、通常の文字幅のまま並べると間隔が広く見えてしまう組み合わせ（例: 「T」と「o」、「A」と「V」、「「」と「「」など）に対し、個別に文字間隔を調整して自然な文字並びにする機能です。',
    appFeatureTip: '「機能」メニュー内の「カーニング」を開き「自動カーニング」を押すと、作図画像から光学的に隙間を自動調整できます。',
    badge: '文章美化',
  },
  {
    id: 'os2-table',
    term: 'OS/2 テーブル & メトリクス',
    reading: 'おーえすつーてーぶる',
    english: 'OS/2 Table / Line Metrics',
    category: 'format',
    shortSummary: 'WindowsやMac、動画ソフトに行間や文字の高さを伝えるフォントデータ規格',
    easyExplanation: 'フォントファイル内に含まれる管理データの一部です。WordやAviUtl、Premiere、ブラウザなどでフォントを使用する際、文字が上下にはみ出したり改行幅が広すぎたりしないよう、文字の太さや行間高さを指示します。',
    appFeatureTip: '「フォント情報」内の「OS/2・hhea 詳細メタデータ」タブで、ウェイト値（100〜900）やアセンダ高度を調整できます。',
  },
  {
    id: 'diagnostics',
    term: 'フォント品質診断 ( Problem Finder )',
    reading: 'ひんしつしんだん',
    english: 'Font Diagnostics / Quality Check',
    category: 'format',
    shortSummary: '全文字の不備（重なり・未閉鎖・浮き上がり・文字欠落）を自動チェックする機能',
    easyExplanation: '制作したフォントにエラー（線が閉じていない、文字が極端に浮いている、文字数が足りないなど）がないかを一括で検査・点検する機能です。',
    appFeatureTip: '上部メニューの「品質診断」を開くと、判定スコアと修正アドバイスを一覧確認して一括修正できます。',
    badge: '安心チェック',
  },
  {
    id: 'ttf-otf',
    term: 'TTF / OTF (フォントファイル)',
    reading: 'てぃーてぃーえふ / おーてぃーえふ',
    english: 'TrueType (.ttf) / OpenType (.otf)',
    category: 'format',
    shortSummary: 'OSや各デザインアプリにインストールして使用できる標準フォント形式',
    easyExplanation: 'Windows、macOS、iPadOS、iOS、および各種制作ソフトウェア（Word、Illustrator、CLIP STUDIO PAINTなど）にインストール可能な標準ファイル形式です。互換性を重視する場合はTTF形式が広く推奨されます。',
    appFeatureTip: '画面右上の「フォント出力」ボタンから、ワンクリックでTTFまたはOTFファイルをダウンロードできます。',
    badge: 'ファイル形式',
  },
  {
    id: 'woff',
    term: 'WOFF (Webフォント)',
    reading: 'うぉふ',
    english: 'Web Open Font Format (.woff / .woff2)',
    category: 'format',
    shortSummary: 'Webブラウザでの表示に最適化された軽量フォント形式',
    easyExplanation: 'Webサイト上で指定フォントを高速に読み込み・表示できるよう圧縮されたWeb専用のフォント形式です。Webサイトやブログに自作フォントを組み込む際に活用されます。',
    appFeatureTip: '「フォント出力」画面でWOFFを選択すると、Webサイト用のCSSコードと一緒にダウンロードできます。',
  },
  {
    id: 'font-weight',
    term: 'ウェイト (太さ・ファミリー)',
    reading: 'うぇいと',
    english: 'Font Weight',
    category: 'basic',
    shortSummary: '同一フォントファミリー内における文字の太さの段階',
    easyExplanation: 'Thin（極細）、Light（細字）、Regular（標準）、Bold（太字）、Black（極太）など、文字の線の太さ（ウェイト）のバリエーションのことです。統一されたデザインで複数の太さを持つフォント群をファミリーと呼びます。',
    appFeatureTip: '「機能」メニューの「複数ウェイト自動生成」を利用すると、作成した文字から最大5段階の太さを一括自動生成できます。',
  },
];
